[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/addon/manifest.json"
  status = 200

[[redirects]]
  from = "/catalog/*"
  to = "/.netlify/functions/addon/catalog/:splat"
  status = 200

[[redirects]]
  from = "/stream/*"
  to = "/.netlify/functions/addon/stream/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/addon/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"