[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/manifest"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/addon/:splat"
  status = 200

[functions.addon]
  external_node_modules = ["stremio-addon-sdk"]

[functions.manifest]
  external_node_modules = ["stremio-addon-sdk"]