[build]
  # This command installs the dependencies from package.json
  command = "npm install"
  # This specifies the directory where your serverless functions are located
  functions = "netlify/functions"

[[redirects]]
  # This rule rewrites all requests to your serverless function
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200