[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/addon"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/addon/:splat"
  status = 200