[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/addon/*"
  to = "/.netlify/functions/addon/:splat"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/addon/manifest.json"
  status = 200